# 1. Define upstream servers
upstream docker_backends {
    zone docker_backends 64k;

    server 10.100.100.200:211 max_conns=1 max_fails=1 fail_timeout=100s;
    # server 10.100.100.101:8082 max_conns=1 max_fails=1 fail_timeout=100s;
    # server 10.100.100.102:8082 max_fails=1 fail_timeout=100s;
    # server 10.100.100.103:8082 max_fails=1 fail_timeout=100s;
    # server 10.100.100.104:8082 max_fails=1 fail_timeout=100s;
    # server 10.100.100.105:8082 max_fails=1 fail_timeout=100s;
}


# 2. Define cache zone
proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=my_cache:256m max_size=10g inactive=60s use_temp_path=off;

server {
    listen 8080;


    # default location: no cache
    location / {
        proxy_pass http://docker_backends;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;


        proxy_cache off;
        add_header X-Cache-Status "DISABLED";
    }


    location /cached-status/ {
        rewrite ^/cached-status/(.*)$ /$1 break;
        proxy_pass http://docker_backends;



        proxy_cache my_cache;
        proxy_cache_key "$scheme$proxy_host$uri$is_args$args";
        proxy_cache_valid 200 60s;
        proxy_cache_use_stale error timeout updating;
        add_header X-Cache-Status $upstream_cache_status;

        proxy_connect_timeout 2s;
        proxy_read_timeout 5s;
    }

    # nginx status
    location /nginx_status {
        stub_status;
        allow 0.0.0.0/0;
        deny all;
    }
}